name: Sync Fork
 
on:
  schedule:
    - cron: '0 2 * * *'        # 每天 UTC 2 点自动运行一次，可根据需要调整
  workflow_dispatch:
 
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v2.0
        with:
          base: main
          head: main
