name: Sync Fork
 
on:
  schedule:
    - cron: '0 2 * * *'        # 每天 UTC 2 点自动运行一次，可根据需要调整
  workflow_dispatch:
 
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Fork Sync
      - uses: tgymnich/fork-sync@v1.2.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
